### ISSUE TITLE
Procedure to override original TI CC2531 driver (temporarily)? 

### ISSUE THREAD

**Issue by netadair** [andrebdo/wireshark-cc2531#2]
I do have a problem where W10 complains about "having the best driver already installed" for that device,
even when manually specifying the winsusb.inf .
Do you have any idea how to (temporarily) circumvent that and get it running?
TIA

**Comment by andrebdo** [comment]
Sorry, I don't know how to do that, or if it is even possible.
I never actually installed the TI driver, I always used the CC2531 device with the WinUsb driver only.
